---
- name: creating user
  hosts: all
  become: true
  become_user: root
  gather_facts: no

  tasks:
    - name: creating new user
      user: 
        name: syed
        home: /home/syed
        shell: /bin/bash

