---
- name: Add or update user password
  hosts: all
  
  tasks:
  - name: Change “syed” password
    user:
      name: syed
      update_password: always
      password: "{{ newpassword|password_hash('sha512’) }}”
