---
- name: Add or update user password
  hosts: all
  
  tasks:
  - name: Change “syedsam” password
    user:
      name: syedsam
      update_password: always
      password: "{{ newpassword|password_hash('sha512’) }}”
