---
- name: check file status
  hosts: all
  
  tasks: 
   - name: checking file status
     stat: 
           path: /tmp/file 
     register: fs

   - name: show result
     debug: 
           msg: file info {{ fs }}


