---
- name: check file status
  hosts: all
  gather_facts: false 
  become: true
  become_user: root
  tasks: 
   - name: checking file status
     stat: 
           path: /tmp/file 
     register: fs

   - name: show result
     debug: 
           msg: file info {{ fs }}

   - name: creating dir
     file: 
       name: creating 
       state: directory
       group: sohail
       owner: sohail 
       mode: 0755
     register: fs1

   - name: checking directory
     debug: 
        msg: directory has been created {{fs1}}

   - name: creating file in directory 
     file:
        name: newfile 
        path: ~/creating/newfile
        state: touch 
     register: fs2

   - name: creation has beeen updated.
     debug: 
        msg: file has been created {{ fs2 }}
 
   - name: adding text in file.
     blockinfile: 
           path: newfile
           block: this is the msg you will see at on of the playbook thanks for my playbook and see you again
     register: fs3 
     
   - name: text has been added in file. 
     debug: 
        msg: text has added {{ fs3 }}
    

  
    
         
         




