---
- name: Git Module with Username Password
  hosts: localhost 
  gather_facts: false 
  vars_prompt: 
        name: username
        prompt: Enter GIT user name Username? 
        private: no 
 
        name: password
        prompt: Enter Password for Git? 
        private: yes 

        name: repo_name
        prompt: Enter repo name ? 
        private: no    
    
  tasks: 
  - name: 
    git: 
     repo: 'https://github.com/syedsam584/{{ repo_name }}.git'
     dest:  /root
     force: no

