---
- name: looping 
  gather_facts: false 
  hosts: all
  vars: 
    users: [nehal, minhaj, saniya, miffu, ifzan] 

  tasks: 
  - name: create users 
    user: 
      name: '{{item}}'
      state: present  
    with_items: '{{users}}'
