---
- name: set_fact
  hosts: all
  tasks: 
  - name: getting fact
    set_fact: 
      our_fact: ansible rocks!
      ansible_distribution: "{{ ansible_distribution | upper }}"
  
  - name: show custom fact
    debug: 
      msg: "{{ our_fact }}"

  - name: show ansible_distribution
    debug: 
      msg: "{{ ansible_distribution }}"

...
