---
- name: testing handlers
  hosts: all 
  
  tasks: 
    - name: installing tree package
      yum: 
        name: "tree"
        state: present 
      notify: display status
    
  handlers: 
    - name: display status
      debug: 
        msg: yes it is installed.   

- hosts: all
  tasks: 
    - name: install httpd 
      yum:
        name: httpd
        state: present 
      notify: start httpd
     
  handlers: 
    - name: start httpd 
      service: 
         name: httpd 
         state: started

...
