- name: Install httpd packages
  yum:
   name: httpd
   state: present

- name: Start httpd
  service:
    name: httpd
    state: started

- name: Open port http on firewall
  firewalld:
     service: http
     permanent: true
     state: enabled

- name: Restart firewalld
  service:
    name: firewalld
    state: reloaded


